# Site settings
title: Shubham Sharma
email: shubh133@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A Personal Website for sharing thoughts and ideas about Technology.
baseurl: "" # the subpath of your site, e.g. /blog/
#slogan: "Simply Smart"
slogan: "Cloud Developer"
url: "http://shubhamsharma.in" # the base hostname & protocol for your site
twitter_username: shubh1337
github_username:  shubham1337
linkedin_username:  https://in.linkedin.com/pub/shubham-sharma/b3/244/761

# Build settings
markdown: kramdown

# Auto Generation of sitemap.xml by GitHub Pages
gems:
    - jekyll-sitemap
    
defaults:
    - scope:
        path: "bower_components/*"
      values:
        sitemap: false
