# Site settings
title: Shubham Sharma
email: shubham_sharma@outlook.com
description: > # this means to ignore newlines until "baseurl:"
    A Personal Blog for sharing Ideas with the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shubhamsharma.in" # the base hostname & protocol for your site
twitter_username: shubh1337
github_username:  shubham1337

# Build settings
markdown: kramdown
